# .github/workflows/frontend.yml

name: Frontend CI/CD

on:
  push:
    branches:
      - master

    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'

  pull_request:
    branches:
      - master

    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'
    if: github.event.pull_request.head.repo.full_name == github.repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.Js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync ./dist/ s3://${{ secrets.S3_BUCKET }}/ --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'

      
